### PR TITLE
Coverage Visualization

### PR DESCRIPTION
**Pull request by kindly**
Front end changes related to #99

### CODE REVIEW

**Review by jpmckinney — COMMENTED** [review]
I think `sentry-sdk` needs to be added in `requirements.in` and re-configured in `settings.py` per https://github.com/OpenDataServices/lib-cove-web/blob/main/CHANGELOG.md#0230---2021-05-12

**Comment by jpmckinney** [comment]
I think you can do the same as cove-ocds: https://github.com/open-contracting/cove-ocds/blob/main/cove_project/settings.py#L20-L36

**Comment by kindly** [comment]
@jpmckinney nice catch!

Do you want any further review this pull request?  The only thing left is the i18n, but leaving that till last just in case of any text changes.

Also you may want to look over the related:
https://github.com/OpenDataServices/lib-cove/pull/89

This has been merged as this pull request needed a version on pypi.

**Review by jpmckinney — APPROVED** [review]
Looks good!

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
