### PR TITLE
requirements: Update Django for security update

### PR DESCRIPTION
**Pull request by Bjwebb**
Potential directory-traversal via uploaded files:
https://docs.djangoproject.com/en/2.2/releases/2.2.21/

### CODE REVIEW

**Review by jpmckinney — APPROVED** [review]

**Comment by Bjwebb** [comment]
I tried to deploy this, but the code seems to expect Django 3.2, although 2.2 is listed in the requirements file. I've rolled back to a commit before the 3.2 work.

**Comment by jpmckinney** [comment]
@Bjwebb Do you mean the deploy was rolled back, or the repository?

**Comment by jpmckinney** [comment]
I've now updated the requirements. I'll try a deploy later. Tests pass though, so I assume it was the new memcache class.

**Comment by Bjwebb** [comment]
Just the deploy. Yes, it was the new memcache class.

**Comment by jpmckinney** [comment]
The new deploy seems to have no issue. I think when I did #90 I forgot to update some dependencies that had pinned Django.

**Comment by jpmckinney** [comment]
Seems like the issue was `server_max_value_length`, which was added in https://github.com/open-contracting/cove-oc4ids/commit/be08e5604da514bc9b72cf996d83a850a5105124 without explanation. I assume the option is specific to the deprecated backend.

Fixed in https://github.com/open-contracting/cove-oc4ids/commit/b8563c1e7c3a70f070795174d6557fe5eaa47abd

**Pull request merged**
